name: playertags
version: 1.0.3
main: io.maloschnikow.playertags.PlayerTags
description: Players can add tags to make their names appear prettier.
author: Maloschnikow
website: https://github.com/Maloschnikow/mc-player-tags
api-version: '1.21.4'

permissions:

  permissions.PlayerTag:
    description: "Allows someone to apply a tag command. (/playertag)"
    default: true

  permissions.clearPlayerTag:
    description: "Allows someone to clear a player's tag."
    default: true

  permissions.customPlayerTag:
    description: "Allows someone to apply a custom tag. (/playertagcustom)"
    default: op

  permissions.setOtherPlayerTag:
    description: "Allows someone to apply a tag to another player."
    default: op

