name: playertags
version: 0.0.1
main: io.maloschnikow.playertags.PlayerTags
description: Adds a player tags.
author: Maloschnikow
api-version: '1.21.1'

permissions:

  permissions.setPlayerTag:
    description: "Allows someone to apply a tag command. (/playertag)"
    default: true

  permissions.clearPlayerTag:
    description: "Allows someone to clear a player's tag."
    default: true

  permissions.customPlayerTag:
    description: "Allows someone to apply a custom tag. (/playertagcustom)"
    default: op

  permissions.setOtherPlayerTag:
    description: "Allows someone to apply a tag to another player."
    default: op

